#!/usr/bin/env bash
# Install and configure HAProxy on Ubuntu

# Update and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Backup default HAProxy config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Set up HAProxy configuration
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << 'EOF'
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend ismaelkiprop.tech
    bind *:80
    default_backend ismaelkiprop.tech

backend ismaelkiprop.tech
    balance roundrobin
    server 453992-web-01 54.146.70.179:80 check
    server 453992-web-02 18.209.180.111:80 check
EOF

# Enable HAProxy to be managed by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy service
sudo service haproxy restart

