#!/bin/bash

# Edit Nginx configuration
sed -i 's/user\s*root;/user nginx;/g' /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart

# Verify Nginx is running as nginx user
ps auxff | grep ngin[x]

# Verify Nginx is listening on port 8080
nc -z 0 8080
